AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Managed Policy to allow listing and reading FIS configs from S3

Parameters:
  BucketNamePrefix:
    Type: String
    Default: fis-test-lambda
    Description: Prefix of the S3 bucket name. Final bucket will be "<prefix>-<accountId>".

Resources:
  FisConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-${AWS::AccountId}"

  S3FisConfigsReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: S3FisConfigsReadPolicy
      Description: Allow listing FisConfigs/ and reading objects in the bucket ${BucketNamePrefix}-${AWS::AccountId}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowListingConfigLocation
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${BucketNamePrefix}-${AWS::AccountId}
            Condition:
              StringLike:
                s3:prefix:
                  - FisConfigs/*
          - Sid: AllowReadingObjectFromConfigLocation
            Effect: Allow
            Action: s3:GetObject
            Resource:
              - !Sub arn:aws:s3:::${BucketNamePrefix}-${AWS::AccountId}/FisConfigs/*

Outputs:
  BucketName:
    Description: The S3 bucket name used for FIS configs
    Value: !Sub "${BucketNamePrefix}-${AWS::AccountId}"
